### ISSUE TITLE
Fix: PostCard - Overlapping text

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#33]
![image](https://github.com/user-attachments/assets/c157cb31-9684-4157-8370-dd3d8d14151f)

When text is to big, it should end with ...

Avoid the overlapping with icons.

**Comment by ianbitt** [comment]
<img width="294" alt="Screenshot 2024-11-11 at 16 28 47" src="https://github.com/user-attachments/assets/df24430a-7f8c-463b-9821-5d95a688740c">

Added a function to limit the characters amount based on the desired amount. I've settled to 25 but it's changeable!

**Comment by trindadetiago** [comment]
![Image](https://github.com/user-attachments/assets/be5138a2-e05c-440d-a4d0-dedbc1ae62a4)

The character amount strategy won't work very well, since there is the responsiveness part. Also, from screen to screen may change.

Go with a different approach.  Use the size of the container. make the container size don't go over the icons.
Then, make the text inside  overflow with ellipse

**Comment by ianbitt** [comment]
Addeed a few changes on the attributes of the <p> element that grants the desired responsiveness. Also, added changed the organization logic from the containers.

![Image](https://github.com/user-attachments/assets/361ae85f-6ca8-4914-90c9-348e2368a5f9)
![Image](https://github.com/user-attachments/assets/ee63566f-f821-4148-9db9-8d5b0450720f)
