### ISSUE TITLE
New Feature: PostCard - Add user information

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#34]
![image](https://github.com/user-attachments/assets/b92584f3-68e0-419d-9c39-662b69bf9e04)

Complete the modal information

**Comment by ianbitt** [comment]
<img width="1440" alt="Screenshot 2024-11-11 at 18 05 45" src="https://github.com/user-attachments/assets/c5cf34ad-e8f2-4f20-bf06-02a2736c0bd4">

Managed to apply an UserCard based on the users that are participating in the project.
