### ISSUE TITLE
New Feature/Edit: User Badge - Increase or allow for size personalization

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#35]
![image](https://github.com/user-attachments/assets/50500889-9644-4051-a6bb-1d1e5b4de5bb)

Make the size of the badge changable. It is too small at the moment.

**Comment by trindadetiago** [comment]
![Image](https://github.com/user-attachments/assets/76fc5fcf-d08c-474e-bd3a-da50ffaa4188)


For context, here's Dribbble's

**Comment by Emysntts** [comment]
I increased the size of the badges and added the "smallSize" Prop to adjust the size of the small badges as needed.

![Image](https://github.com/user-attachments/assets/1f6e4267-1a78-4071-84fd-b3c3b4c11ccb)
