### ISSUE TITLE
Fix: Search Filter - Filter not aligning it self when responsive

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#36]
![image](https://github.com/user-attachments/assets/5c4f6b88-815e-4d37-93c4-66e49c42b9d3)

When the width of the screen is small, the filter is not well aligned.

**Comment by Emysntts** [comment]
“Filter” button alignment has been corrected. Additionally, the background color of elements in the dark mode has been adjusted to match the intended shade of black.

![Image](https://github.com/user-attachments/assets/94dc1626-4894-4054-894a-5b8b9e514112)
![Image](https://github.com/user-attachments/assets/f58f13ba-adea-4881-b165-f29f1b7722d5)
