### ISSUE TITLE
Improvement: Project Card - Change details and component Name

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#39]
![image](https://github.com/user-attachments/assets/bd7886af-ee3c-454c-8123-8fb66aae6ae9)

![image](https://github.com/user-attachments/assets/9fefadbf-95dc-458f-b4c4-68df04cfc4b4)

The first image is dribbble, the second is Aquario. Make Aquario more similar to dribbble, applying a bigger height and smaller image sizes.

Also, change the name of the component to "ProjectCard"

**Comment by ianbitt** [comment]
<img width="293" alt="Screenshot 2024-11-11 at 16 52 44" src="https://github.com/user-attachments/assets/910f9a71-e0b2-43eb-ac27-15ea7cc66080">

Adjusted the sizing of the images and the height of the ProstCard. Also changed the name of the component to ProjectCard
