### ISSUE TITLE
Improve: Project Card - Project Card responsiveness

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#46]
![image](https://github.com/user-attachments/assets/c55a8b02-a561-446b-b15f-efed800f1506)

At users page, you can see its responsiveness could improve.
(I actually did some changes on it, but it wasn't enough)

**Comment by ianbitt** [comment]
<img width="1236" alt="Screenshot 2024-11-12 at 20 20 38" src="https://github.com/user-attachments/assets/89b9024e-6a55-445d-a39c-0b42a6c401cb">
<img width="815" alt="Screenshot 2024-11-12 at 20 21 36" src="https://github.com/user-attachments/assets/ab214c41-cb9c-4221-945c-57759e0410c6">
<img width="698" alt="Screenshot 2024-11-12 at 20 20 56" src="https://github.com/user-attachments/assets/46184d4a-267c-43c4-b445-83cbcc479c39">
<img width="397" alt="Screenshot 2024-11-12 at 20 21 16" src="https://github.com/user-attachments/assets/534f9498-e3ec-4060-911d-5b7e667fdcdf">

Changed it so it doesen't overlay one projectcard over the other
