### ISSUE TITLE
Improvement: Filter Bar - Usuarios Page

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#54]
![image](https://github.com/user-attachments/assets/aafa8a3a-0d9f-44e0-9519-a5a119828c5b)

This is usuarios page

![image](https://github.com/user-attachments/assets/bb325462-f2cc-4cb1-adea-fdffedd4632f)

This is the other page's filter.

The size of the second page is better. Apply the same component at Usuario's page, without the part with the button filter.

**Comment by trindadetiago** [comment]
![image](https://github.com/user-attachments/assets/fec5ee71-0265-40f1-8272-95208c9ec86b)
to be clear, this is the part to be edited

**Comment by ianbitt** [comment]
![Image](https://github.com/user-attachments/assets/9c806939-b98c-46e5-a215-658559e107a1)
Corrected it and made it smaller, also changed the logic to make it look better adding two different div's dividing the search bar and the index

**Comment by ianbitt** [comment]
![Image](https://github.com/user-attachments/assets/664b5644-062f-4c44-92ec-1853fc25c677)
Correcteed it by making it smaller as you requested. Also, changed the logic of this element to make it look better. Splitted into two divs  (the searchbar and the index)

**Comment by ianbitt** [comment]
also, the "Laboratórios" div is lit up because when taking the screenshot my cursor was on top of it!
