### ISSUE TITLE
Improvement and Fix: User Card - Usuarios Page

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#56]
![image](https://github.com/user-attachments/assets/da5d2e8f-44f3-447f-9ced-e5031c8fc192)

Notice two things: The overlapping images when the responsiveness is within a specific range; and the error that appears:

![image](https://github.com/user-attachments/assets/e91e57f4-c80b-408e-9b61-caf2cce9d0fd)

Work on both.

**Comment by ianbitt** [comment]
Error has been corrected with a verification whether the page is or not undefined.
