### ISSUE TITLE
New Page: Login

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#57]
Create a login page.

You can use shadcn's example of one: https://ui.shadcn.com/examples/authentication

Try to follow the same visual style of the other pages, but no need to make it complicated.

**Comment by Emysntts** [comment]
Design suggestion for login page

![image](https://github.com/user-attachments/assets/6000733e-3291-4e4e-995f-8d3405c37f9c)![image](https://github.com/user-attachments/assets/c86d6d4b-7fd5-45f4-b161-8dfb7509e466)
![image](https://github.com/user-attachments/assets/d083e66e-8c22-4fd5-9b1c-68ed4576d9b9)
