### ISSUE TITLE
New Page: Cursos Guias - FAQ

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#58]
![image](https://github.com/user-attachments/assets/10109b70-5857-47ed-be82-567d583e2dbb)

At FAQ, replace all the content with this page above.

Add the three courses:
- Ciência da Computação
- Engenharia da Computação
- Ciência de Dados e IA

Add them individually, intead of them in the Center.

So the first Center would be Ciencia da Computação, the second Engenharia, the third CDIA. (Temporary)

**Comment by matheusfer0902** [comment]
Development of the FAQ Page.


![WhatsApp Image 2024-12-16 at 10 50 47](https://github.com/user-attachments/assets/393335b7-ef10-4e43-9bed-da1b2ab6f6dd)



![WhatsApp Image 2024-12-16 at 10 51 58](https://github.com/user-attachments/assets/15d26541-c2f9-42d7-88c2-6e6f4d6a77f4)
