### ISSUE TITLE
Fix: Post Card - Icons in darkmode not visible

### ISSUE THREAD

**Issue by trindadetiago** [trindadetiago/aquario#62]
![image](https://github.com/user-attachments/assets/2231fb05-75cb-45a4-a652-f1256724d086)

Icons are hard to see in darkmode.

**Comment by ianbitt** [comment]
![Image](https://github.com/user-attachments/assets/05d75cb1-1de4-4aee-97aa-b51f3d94c0fc)

Whenever the dark mode is activated, now it changes the bg of the icons to black.
